In [1]:
import numpy as np
import torch

WHY TENSORS


In [2]:
import time
N = 100000
lista = list(range(N))
listb = list(range(N))

na = np.array(lista)
nb = np.array(listb)

In [3]:
start = time.perf_counter()
dlist = 0
for i in range(N):
  dlist+=lista[i]*listb[i]
end = time.perf_counter()

print(f"Time for list {end-start}")

Time for list 0.018397800042293966


In [4]:
start = time.perf_counter()
dot_numpy = np.dot(na , nb)
end = time.perf_counter()

print(f"Time for numpy {end-start}")


Time for numpy 0.0006865999894216657


BASIC NUMPY

In [5]:
a = np.array([1 , 2, 3, 4])
print(a.shape)

(4,)


In [6]:
b = np.array([[1,2] , [3,4]])
print(b.shape)

(2, 2)


BASIC TORCH TENSOR


In [7]:
a_t = torch.tensor([1 , 2 , 3 , 4])
print(a_t.shape)

torch.Size([4])


In [8]:
b_t = torch.tensor([[1 , 2] , [3 ,4]])
print(b_t.shape)

torch.Size([2, 2])


NUMPY OPERATIONS

In [9]:
print(na + nb)
print(na * nb)

[     0      2      4 ... 199994 199996 199998]
[         0          1          4 ... 1409465417 1409665412 1409865409]


In [10]:
print(a[1:2])
print(b[ : , 1:])

[2]
[[2]
 [4]]


TENSOR TORCH OPERATIONS

In [11]:
print(a_t ** 3)

tensor([ 1,  8, 27, 64])


In [12]:
print(a_t[:2])
print(b_t[ : , 1:2])
c_t = torch.from_numpy(na)
print(c_t)

tensor([1, 2])
tensor([[2],
        [4]])
tensor([    0,     1,     2,  ..., 99997, 99998, 99999], dtype=torch.int32)


In [13]:
shape = (5 , 5 , )
temp = torch.rand(shape)
print(temp)
print(torch.ones(shape))

tensor([[0.7926, 0.3586, 0.6452, 0.7482, 0.3422],
        [0.2275, 0.5579, 0.8783, 0.3328, 0.0512],
        [0.5591, 0.8238, 0.4941, 0.6863, 0.4078],
        [0.0769, 0.6215, 0.1129, 0.9958, 0.9704],
        [0.8860, 0.0926, 0.3145, 0.9351, 0.1873]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [14]:
print(torch.cat([temp , temp]))

tensor([[0.7926, 0.3586, 0.6452, 0.7482, 0.3422],
        [0.2275, 0.5579, 0.8783, 0.3328, 0.0512],
        [0.5591, 0.8238, 0.4941, 0.6863, 0.4078],
        [0.0769, 0.6215, 0.1129, 0.9958, 0.9704],
        [0.8860, 0.0926, 0.3145, 0.9351, 0.1873],
        [0.7926, 0.3586, 0.6452, 0.7482, 0.3422],
        [0.2275, 0.5579, 0.8783, 0.3328, 0.0512],
        [0.5591, 0.8238, 0.4941, 0.6863, 0.4078],
        [0.0769, 0.6215, 0.1129, 0.9958, 0.9704],
        [0.8860, 0.0926, 0.3145, 0.9351, 0.1873]])


In [15]:
print(torch.sum(a_t))

tensor(10)


MASKING - NUMPY

In [16]:
mask = a>2
print(mask)
print(a[mask])

[False False  True  True]
[3 4]


In [17]:
print(mask)
print(a_t[mask])

[False False  True  True]
tensor([3, 4])


EXTRACTING SUB TENSORS

In [18]:
mat = torch.tensor([[1 , 2, 3] ,
                   [4 , 5 ,6 ] ,
                   [7 , 8 , 9]])
sub = mat[:2 , 1:]
print(sub)

tensor([[2, 3],
        [5, 6]])


SHAPE MANIPULATION

In [19]:
x = torch.arange(6)
print(x)

y = x.view(2 , 3)
print(y)

z = x.reshape(2 , 3)
print(z)

tensor([0, 1, 2, 3, 4, 5])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [20]:
#UNSQUEEZE -> ADDS DIMENSION
x = torch.tensor([1, 2, 3])
print(x.shape)

y = x.unsqueeze(0)
print(y.shape)

z = x.unsqueeze(1)
print(z.shape)


torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


In [21]:
#SQUEEZE -> REMOVES DIMENSION
a = torch.randn(1, 3, 1, 5)
print(a.shape)

b = a.squeeze()
print(b.shape)


torch.Size([1, 3, 1, 5])
torch.Size([3, 5])


DIFFERENCE BETWEEN RESHAPE OF PYTORCH AND NUMPY


In [22]:
#NUMPY
x = np.arange(6).reshape(2, 3)
y = x.T
z = y.reshape(6)

print(z)

[0 3 1 4 2 5]


In [23]:
#PYTORCH
x = torch.arange(6).reshape(2, 3)
y = x.t()

z = y.view(6)
#gives error as memory is non contiguous

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

BROADCASTING


In [24]:
#SCALAR

x = torch.tensor([1, 2, 3])
y = x + 10
print(y)


tensor([11, 12, 13])


In [25]:
#VECTOR
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

y = torch.tensor([10, 20, 30])

z = x + y
print(z)


tensor([[11, 22, 33],
        [14, 25, 36]])


In-place vs Out-of-place Operations

In [26]:
#Out of space -> creates new tensors
#In place -> modifies at same memory location
x = torch.tensor([1., 2., 3.])

y = x + 1
print(x)
print(y)


tensor([1., 2., 3.])
tensor([2., 3., 4.])


In [27]:
x = torch.tensor([1., 2., 3.])
y = x

x.add_(1)
print(y)


tensor([2., 3., 4.])
